export const tradingCallbackAbi = [
  {
    type: 'function',
    name: 'closeTradeMarketCallback',
    inputs: [
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'correctSl',
    inputs: [
      { name: 'openPrice', type: 'uint256', internalType: 'uint256' },
      { name: 'leverage', type: 'uint256', internalType: 'uint256' },
      { name: 'sl', type: 'uint256', internalType: 'uint256' },
      { name: 'buy', type: 'bool', internalType: 'bool' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'correctTp',
    inputs: [
      { name: 'openPrice', type: 'uint256', internalType: 'uint256' },
      { name: 'leverage', type: 'uint256', internalType: 'uint256' },
      { name: 'tp', type: 'uint256', internalType: 'uint256' },
      { name: 'buy', type: 'bool', internalType: 'bool' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'executeLimitCloseOrderCallback',
    inputs: [
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'executeLimitOpenOrderCallback',
    inputs: [
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'openTradeMarketCallback',
    inputs: [
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'transferFromVault',
    inputs: [
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'updateMarginCallback',
    inputs: [
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'updateSlCallback',
    inputs: [
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'vaultFeeP',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'AddressUpdated',
    inputs: [
      {
        name: 'name',
        type: 'string',
        indexed: false,
        internalType: 'string',
      },
      {
        name: 'a',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Done',
    inputs: [
      {
        name: 'done',
        type: 'bool',
        indexed: false,
        internalType: 'bool',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'FeeUpdated',
    inputs: [
      {
        name: '_vaultFeeP',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: '_liqFeeP',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: '_liqTotalFeeP',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'LimitExecuted',
    inputs: [
      {
        name: 'orderId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'limitIndex',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 't',
        type: 'tuple',
        indexed: false,
        internalType: 'struct ITradingStorage.Trade',
        components: [
          { name: 'trader', type: 'address', internalType: 'address' },
          {
            name: 'pairIndex',
            type: 'uint256',
            internalType: 'uint256',
          },
          { name: 'index', type: 'uint256', internalType: 'uint256' },
          {
            name: 'initialPosToken',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'positionSizeUSDC',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'openPrice',
            type: 'uint256',
            internalType: 'uint256',
          },
          { name: 'buy', type: 'bool', internalType: 'bool' },
          {
            name: 'leverage',
            type: 'uint256',
            internalType: 'uint256',
          },
          { name: 'tp', type: 'uint256', internalType: 'uint256' },
          { name: 'sl', type: 'uint256', internalType: 'uint256' },
          {
            name: 'timestamp',
            type: 'uint256',
            internalType: 'uint256',
          },
        ],
      },
      {
        name: 'orderType',
        type: 'uint8',
        indexed: false,
        internalType: 'enum ITradingStorage.LimitOrder',
      },
      {
        name: 'price',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'positionSizeUSDC',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'percentProfit',
        type: 'int256',
        indexed: false,
        internalType: 'int256',
      },
      {
        name: 'usdcSentToTrader',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'MarginUpdated',
    inputs: [
      {
        name: 'trader',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'pairIndex',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'index',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'newSl',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'timestamp',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'MarketExecuted',
    inputs: [
      {
        name: 'orderId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 't',
        type: 'tuple',
        indexed: false,
        internalType: 'struct ITradingStorage.Trade',
        components: [
          { name: 'trader', type: 'address', internalType: 'address' },
          {
            name: 'pairIndex',
            type: 'uint256',
            internalType: 'uint256',
          },
          { name: 'index', type: 'uint256', internalType: 'uint256' },
          {
            name: 'initialPosToken',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'positionSizeUSDC',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'openPrice',
            type: 'uint256',
            internalType: 'uint256',
          },
          { name: 'buy', type: 'bool', internalType: 'bool' },
          {
            name: 'leverage',
            type: 'uint256',
            internalType: 'uint256',
          },
          { name: 'tp', type: 'uint256', internalType: 'uint256' },
          { name: 'sl', type: 'uint256', internalType: 'uint256' },
          {
            name: 'timestamp',
            type: 'uint256',
            internalType: 'uint256',
          },
        ],
      },
      {
        name: 'open',
        type: 'bool',
        indexed: false,
        internalType: 'bool',
      },
      {
        name: 'price',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'positionSizeUSDC',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'percentProfit',
        type: 'int256',
        indexed: false,
        internalType: 'int256',
      },
      {
        name: 'usdcSentToTrader',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'MarketOpenCanceled',
    inputs: [
      {
        name: 'orderId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'trader',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'pairIndex',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Pause',
    inputs: [
      {
        name: 'paused',
        type: 'bool',
        indexed: false,
        internalType: 'bool',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SlUpdated',
    inputs: [
      {
        name: 'orderId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'trader',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'pairIndex',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'index',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'newSl',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
] as const;
