export const tradingStorageAbi = [
  { type: 'constructor', inputs: [], stateMutability: 'nonpayable' },
  {
    type: 'function',
    name: 'addTradingContract',
    inputs: [{ name: '__trading', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'applyReferralAndPnlFee',
    inputs: [
      { name: '_trader', type: 'address', internalType: 'address' },
      { name: '_fees', type: 'uint256', internalType: 'uint256' },
      {
        name: '_leveragedPosition',
        type: 'uint256',
        internalType: 'uint256',
      },
      { name: '_isPnl', type: 'bool', internalType: 'bool' },
      { name: '_pairIndex', type: 'uint256', internalType: 'uint256' },
      {
        name: '_percentProfit',
        type: 'int256',
        internalType: 'int256',
      },
      { name: '_collateral', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'blockOI',
    inputs: [
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'callbacks',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'claimFees',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'claimRebate',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'dev',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'devFeesUSDC',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'firstEmptyOpenLimitIndex',
    inputs: [
      { name: 'trader', type: 'address', internalType: 'address' },
      { name: 'pairIndex', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: 'index', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'firstEmptyTradeIndex',
    inputs: [
      { name: 'trader', type: 'address', internalType: 'address' },
      { name: 'pairIndex', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: 'index', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'forceUnregisterPendingMarketOrder',
    inputs: [{ name: '_id', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getOpenLimitOrder',
    inputs: [
      { name: '_trader', type: 'address', internalType: 'address' },
      { name: '_pairIndex', type: 'uint256', internalType: 'uint256' },
      { name: '_index', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct ITradingStorage.OpenLimitOrder',
        components: [
          { name: 'trader', type: 'address', internalType: 'address' },
          {
            name: 'pairIndex',
            type: 'uint256',
            internalType: 'uint256',
          },
          { name: 'index', type: 'uint256', internalType: 'uint256' },
          {
            name: 'positionSize',
            type: 'uint256',
            internalType: 'uint256',
          },
          { name: 'buy', type: 'bool', internalType: 'bool' },
          {
            name: 'leverage',
            type: 'uint256',
            internalType: 'uint256',
          },
          { name: 'tp', type: 'uint256', internalType: 'uint256' },
          { name: 'sl', type: 'uint256', internalType: 'uint256' },
          { name: 'price', type: 'uint256', internalType: 'uint256' },
          {
            name: 'slippageP',
            type: 'uint256',
            internalType: 'uint256',
          },
          { name: 'block', type: 'uint256', internalType: 'uint256' },
          {
            name: 'executionFee',
            type: 'uint256',
            internalType: 'uint256',
          },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getOpenLimitOrders',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'tuple[]',
        internalType: 'struct ITradingStorage.OpenLimitOrder[]',
        components: [
          { name: 'trader', type: 'address', internalType: 'address' },
          {
            name: 'pairIndex',
            type: 'uint256',
            internalType: 'uint256',
          },
          { name: 'index', type: 'uint256', internalType: 'uint256' },
          {
            name: 'positionSize',
            type: 'uint256',
            internalType: 'uint256',
          },
          { name: 'buy', type: 'bool', internalType: 'bool' },
          {
            name: 'leverage',
            type: 'uint256',
            internalType: 'uint256',
          },
          { name: 'tp', type: 'uint256', internalType: 'uint256' },
          { name: 'sl', type: 'uint256', internalType: 'uint256' },
          { name: 'price', type: 'uint256', internalType: 'uint256' },
          {
            name: 'slippageP',
            type: 'uint256',
            internalType: 'uint256',
          },
          { name: 'block', type: 'uint256', internalType: 'uint256' },
          {
            name: 'executionFee',
            type: 'uint256',
            internalType: 'uint256',
          },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getPendingOrderIds',
    inputs: [{ name: '_trader', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256[]', internalType: 'uint256[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getUsdOI',
    inputs: [],
    outputs: [{ name: '', type: 'uint256[2]', internalType: 'uint256[2]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'gov',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'govFeesUSDC',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'govTreasury',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'handleDevGovFees',
    inputs: [
      { name: '_trader', type: 'address', internalType: 'address' },
      { name: '_pairIndex', type: 'uint256', internalType: 'uint256' },
      {
        name: '_leveragedPositionSize',
        type: 'uint256',
        internalType: 'uint256',
      },
      { name: '_usdc', type: 'bool', internalType: 'bool' },
      { name: '_fullFee', type: 'bool', internalType: 'bool' },
      { name: '_buy', type: 'bool', internalType: 'bool' },
    ],
    outputs: [
      {
        name: 'feeAfterRebate',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'hasOpenLimitOrder',
    inputs: [
      { name: 'trader', type: 'address', internalType: 'address' },
      { name: 'pairIndex', type: 'uint256', internalType: 'uint256' },
      { name: 'index', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'incrementClosingFees',
    inputs: [
      { name: 'devFees', type: 'uint256', internalType: 'uint256' },
      { name: 'govFees', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'initialize',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'isTradingContract',
    inputs: [{ name: '', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isValidOI',
    inputs: [
      { name: '_pairIndex', type: 'uint256', internalType: 'uint256' },
      { name: 'buy', type: 'bool', internalType: 'bool' },
      { name: 'leveragedPos', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'maxOpenInterest',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'maxPendingMarketOrders',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'maxTradesPerPair',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'openInterestUSDC',
    inputs: [
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'openLimitOrderIds',
    inputs: [
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'openLimitOrders',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      { name: 'trader', type: 'address', internalType: 'address' },
      { name: 'pairIndex', type: 'uint256', internalType: 'uint256' },
      { name: 'index', type: 'uint256', internalType: 'uint256' },
      {
        name: 'positionSize',
        type: 'uint256',
        internalType: 'uint256',
      },
      { name: 'buy', type: 'bool', internalType: 'bool' },
      { name: 'leverage', type: 'uint256', internalType: 'uint256' },
      { name: 'tp', type: 'uint256', internalType: 'uint256' },
      { name: 'sl', type: 'uint256', internalType: 'uint256' },
      { name: 'price', type: 'uint256', internalType: 'uint256' },
      { name: 'slippageP', type: 'uint256', internalType: 'uint256' },
      { name: 'block', type: 'uint256', internalType: 'uint256' },
      { name: 'executionFee', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'openLimitOrdersCount',
    inputs: [
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'openTrades',
    inputs: [
      { name: '_trader', type: 'address', internalType: 'address' },
      { name: '_pairIndex', type: 'uint256', internalType: 'uint256' },
      { name: '_index', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct ITradingStorage.Trade',
        components: [
          { name: 'trader', type: 'address', internalType: 'address' },
          {
            name: 'pairIndex',
            type: 'uint256',
            internalType: 'uint256',
          },
          { name: 'index', type: 'uint256', internalType: 'uint256' },
          {
            name: 'initialPosToken',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'positionSizeUSDC',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'openPrice',
            type: 'uint256',
            internalType: 'uint256',
          },
          { name: 'buy', type: 'bool', internalType: 'bool' },
          {
            name: 'leverage',
            type: 'uint256',
            internalType: 'uint256',
          },
          { name: 'tp', type: 'uint256', internalType: 'uint256' },
          { name: 'sl', type: 'uint256', internalType: 'uint256' },
          {
            name: 'timestamp',
            type: 'uint256',
            internalType: 'uint256',
          },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'openTradesCount',
    inputs: [
      { name: '_trader', type: 'address', internalType: 'address' },
      { name: '_pairIndex', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'openTradesInfo',
    inputs: [
      { name: '_trader', type: 'address', internalType: 'address' },
      { name: '_pairIndex', type: 'uint256', internalType: 'uint256' },
      { name: '_index', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct ITradingStorage.TradeInfo',
        components: [
          {
            name: 'openInterestUSDC',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'tpLastUpdated',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'slLastUpdated',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'beingMarketClosed',
            type: 'bool',
            internalType: 'bool',
          },
          {
            name: 'lossProtection',
            type: 'uint256',
            internalType: 'uint256',
          },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pairLongOI',
    inputs: [{ name: '_pairIndex', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pairOI',
    inputs: [{ name: '_pairIndex', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pairShortOI',
    inputs: [{ name: '_pairIndex', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pairTraders',
    inputs: [
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pairTradersArray',
    inputs: [{ name: '_pairIndex', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'address[]', internalType: 'address[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pairTradersId',
    inputs: [
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pendingMarketCloseCount',
    inputs: [
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pendingMarketOpenCount',
    inputs: [
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pendingOrderIds',
    inputs: [
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pendingOrderIdsCount',
    inputs: [{ name: '_trader', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'priceAggregator',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract IPriceAggregator',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'rebates',
    inputs: [{ name: '', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'referral',
    inputs: [],
    outputs: [
      { name: '', type: 'address', internalType: 'contract IReferral' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'registerPartialTrade',
    inputs: [
      { name: 'trader', type: 'address', internalType: 'address' },
      { name: 'pairIndex', type: 'uint256', internalType: 'uint256' },
      { name: 'index', type: 'uint256', internalType: 'uint256' },
      {
        name: '_amountReduced',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'removeTradingContract',
    inputs: [{ name: '__trading', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'reqIDpendingLimitOrder',
    inputs: [{ name: 'orderId', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct ITradingStorage.PendingLimitOrder',
        components: [
          { name: 'trader', type: 'address', internalType: 'address' },
          {
            name: 'pairIndex',
            type: 'uint256',
            internalType: 'uint256',
          },
          { name: 'index', type: 'uint256', internalType: 'uint256' },
          {
            name: 'orderType',
            type: 'uint8',
            internalType: 'enum ITradingStorage.LimitOrder',
          },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'reqIDpendingMarketOrder',
    inputs: [{ name: 'orderId', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct ITradingStorage.PendingMarketOrder',
        components: [
          {
            name: 'trade',
            type: 'tuple',
            internalType: 'struct ITradingStorage.Trade',
            components: [
              {
                name: 'trader',
                type: 'address',
                internalType: 'address',
              },
              {
                name: 'pairIndex',
                type: 'uint256',
                internalType: 'uint256',
              },
              {
                name: 'index',
                type: 'uint256',
                internalType: 'uint256',
              },
              {
                name: 'initialPosToken',
                type: 'uint256',
                internalType: 'uint256',
              },
              {
                name: 'positionSizeUSDC',
                type: 'uint256',
                internalType: 'uint256',
              },
              {
                name: 'openPrice',
                type: 'uint256',
                internalType: 'uint256',
              },
              { name: 'buy', type: 'bool', internalType: 'bool' },
              {
                name: 'leverage',
                type: 'uint256',
                internalType: 'uint256',
              },
              { name: 'tp', type: 'uint256', internalType: 'uint256' },
              { name: 'sl', type: 'uint256', internalType: 'uint256' },
              {
                name: 'timestamp',
                type: 'uint256',
                internalType: 'uint256',
              },
            ],
          },
          { name: 'block', type: 'uint256', internalType: 'uint256' },
          {
            name: 'wantedPrice',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'slippageP',
            type: 'uint256',
            internalType: 'uint256',
          },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'requestGov',
    inputs: [{ name: '_gov', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'requestedGov',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'setCallbacks',
    inputs: [{ name: '__callbacks', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setDev',
    inputs: [{ name: '_dev', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setGov',
    inputs: [{ name: '_newGov', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setGovTreasury',
    inputs: [
      { name: '_govTreasury', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setMaxPendingMarketOrders',
    inputs: [
      {
        name: '_maxPendingMarketOrders',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setMaxTradesPerPair',
    inputs: [
      {
        name: '_maxTradesPerPair',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setPriceAggregator',
    inputs: [{ name: '_aggregator', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setReferral',
    inputs: [{ name: '_refferal', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setTrading',
    inputs: [{ name: '__trading', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setTvlCap',
    inputs: [{ name: '_newCap', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setUSDC',
    inputs: [{ name: '_token', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setVaultManager',
    inputs: [
      {
        name: '_vaultManager',
        type: 'address',
        internalType: 'address',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'storeOpenLimitOrder',
    inputs: [
      {
        name: 'o',
        type: 'tuple',
        internalType: 'struct ITradingStorage.OpenLimitOrder',
        components: [
          { name: 'trader', type: 'address', internalType: 'address' },
          {
            name: 'pairIndex',
            type: 'uint256',
            internalType: 'uint256',
          },
          { name: 'index', type: 'uint256', internalType: 'uint256' },
          {
            name: 'positionSize',
            type: 'uint256',
            internalType: 'uint256',
          },
          { name: 'buy', type: 'bool', internalType: 'bool' },
          {
            name: 'leverage',
            type: 'uint256',
            internalType: 'uint256',
          },
          { name: 'tp', type: 'uint256', internalType: 'uint256' },
          { name: 'sl', type: 'uint256', internalType: 'uint256' },
          { name: 'price', type: 'uint256', internalType: 'uint256' },
          {
            name: 'slippageP',
            type: 'uint256',
            internalType: 'uint256',
          },
          { name: 'block', type: 'uint256', internalType: 'uint256' },
          {
            name: 'executionFee',
            type: 'uint256',
            internalType: 'uint256',
          },
        ],
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'storePendingLimitOrder',
    inputs: [
      {
        name: '_limitOrder',
        type: 'tuple',
        internalType: 'struct ITradingStorage.PendingLimitOrder',
        components: [
          { name: 'trader', type: 'address', internalType: 'address' },
          {
            name: 'pairIndex',
            type: 'uint256',
            internalType: 'uint256',
          },
          { name: 'index', type: 'uint256', internalType: 'uint256' },
          {
            name: 'orderType',
            type: 'uint8',
            internalType: 'enum ITradingStorage.LimitOrder',
          },
        ],
      },
      { name: '_orderId', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'storePendingMarketOrder',
    inputs: [
      {
        name: '_order',
        type: 'tuple',
        internalType: 'struct ITradingStorage.PendingMarketOrder',
        components: [
          {
            name: 'trade',
            type: 'tuple',
            internalType: 'struct ITradingStorage.Trade',
            components: [
              {
                name: 'trader',
                type: 'address',
                internalType: 'address',
              },
              {
                name: 'pairIndex',
                type: 'uint256',
                internalType: 'uint256',
              },
              {
                name: 'index',
                type: 'uint256',
                internalType: 'uint256',
              },
              {
                name: 'initialPosToken',
                type: 'uint256',
                internalType: 'uint256',
              },
              {
                name: 'positionSizeUSDC',
                type: 'uint256',
                internalType: 'uint256',
              },
              {
                name: 'openPrice',
                type: 'uint256',
                internalType: 'uint256',
              },
              { name: 'buy', type: 'bool', internalType: 'bool' },
              {
                name: 'leverage',
                type: 'uint256',
                internalType: 'uint256',
              },
              { name: 'tp', type: 'uint256', internalType: 'uint256' },
              { name: 'sl', type: 'uint256', internalType: 'uint256' },
              {
                name: 'timestamp',
                type: 'uint256',
                internalType: 'uint256',
              },
            ],
          },
          { name: 'block', type: 'uint256', internalType: 'uint256' },
          {
            name: 'wantedPrice',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'slippageP',
            type: 'uint256',
            internalType: 'uint256',
          },
        ],
      },
      { name: '_id', type: 'uint256', internalType: 'uint256' },
      { name: '_open', type: 'bool', internalType: 'bool' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'storeTrade',
    inputs: [
      {
        name: '_trade',
        type: 'tuple',
        internalType: 'struct ITradingStorage.Trade',
        components: [
          { name: 'trader', type: 'address', internalType: 'address' },
          {
            name: 'pairIndex',
            type: 'uint256',
            internalType: 'uint256',
          },
          { name: 'index', type: 'uint256', internalType: 'uint256' },
          {
            name: 'initialPosToken',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'positionSizeUSDC',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'openPrice',
            type: 'uint256',
            internalType: 'uint256',
          },
          { name: 'buy', type: 'bool', internalType: 'bool' },
          {
            name: 'leverage',
            type: 'uint256',
            internalType: 'uint256',
          },
          { name: 'tp', type: 'uint256', internalType: 'uint256' },
          { name: 'sl', type: 'uint256', internalType: 'uint256' },
          {
            name: 'timestamp',
            type: 'uint256',
            internalType: 'uint256',
          },
        ],
      },
      {
        name: '_tradeInfo',
        type: 'tuple',
        internalType: 'struct ITradingStorage.TradeInfo',
        components: [
          {
            name: 'openInterestUSDC',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'tpLastUpdated',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'slLastUpdated',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'beingMarketClosed',
            type: 'bool',
            internalType: 'bool',
          },
          {
            name: 'lossProtection',
            type: 'uint256',
            internalType: 'uint256',
          },
        ],
      },
      { name: 'isPnl', type: 'bool', internalType: 'bool' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'totalOI',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'trading',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'transferUSDC',
    inputs: [
      { name: '_from', type: 'address', internalType: 'address' },
      { name: '_to', type: 'address', internalType: 'address' },
      { name: '_amount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'tvlCap',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'unregisterOpenLimitOrder',
    inputs: [
      { name: '_trader', type: 'address', internalType: 'address' },
      { name: '_pairIndex', type: 'uint256', internalType: 'uint256' },
      { name: '_index', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'unregisterPendingLimitOrder',
    inputs: [{ name: '_order', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'unregisterPendingMarketOrder',
    inputs: [
      { name: '_id', type: 'uint256', internalType: 'uint256' },
      { name: '_open', type: 'bool', internalType: 'bool' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'unregisterTrade',
    inputs: [
      { name: 'trader', type: 'address', internalType: 'address' },
      { name: 'pairIndex', type: 'uint256', internalType: 'uint256' },
      { name: 'index', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'updateOpenLimitOrder',
    inputs: [
      {
        name: '_o',
        type: 'tuple',
        internalType: 'struct ITradingStorage.OpenLimitOrder',
        components: [
          { name: 'trader', type: 'address', internalType: 'address' },
          {
            name: 'pairIndex',
            type: 'uint256',
            internalType: 'uint256',
          },
          { name: 'index', type: 'uint256', internalType: 'uint256' },
          {
            name: 'positionSize',
            type: 'uint256',
            internalType: 'uint256',
          },
          { name: 'buy', type: 'bool', internalType: 'bool' },
          {
            name: 'leverage',
            type: 'uint256',
            internalType: 'uint256',
          },
          { name: 'tp', type: 'uint256', internalType: 'uint256' },
          { name: 'sl', type: 'uint256', internalType: 'uint256' },
          { name: 'price', type: 'uint256', internalType: 'uint256' },
          {
            name: 'slippageP',
            type: 'uint256',
            internalType: 'uint256',
          },
          { name: 'block', type: 'uint256', internalType: 'uint256' },
          {
            name: 'executionFee',
            type: 'uint256',
            internalType: 'uint256',
          },
        ],
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'updateSl',
    inputs: [
      { name: '_trader', type: 'address', internalType: 'address' },
      { name: '_pairIndex', type: 'uint256', internalType: 'uint256' },
      { name: '_index', type: 'uint256', internalType: 'uint256' },
      { name: '_newSl', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'updateTp',
    inputs: [
      { name: '_trader', type: 'address', internalType: 'address' },
      { name: '_pairIndex', type: 'uint256', internalType: 'uint256' },
      { name: '_index', type: 'uint256', internalType: 'uint256' },
      { name: '_newTp', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'updateTrade',
    inputs: [
      {
        name: '_t',
        type: 'tuple',
        internalType: 'struct ITradingStorage.Trade',
        components: [
          { name: 'trader', type: 'address', internalType: 'address' },
          {
            name: 'pairIndex',
            type: 'uint256',
            internalType: 'uint256',
          },
          { name: 'index', type: 'uint256', internalType: 'uint256' },
          {
            name: 'initialPosToken',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'positionSizeUSDC',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'openPrice',
            type: 'uint256',
            internalType: 'uint256',
          },
          { name: 'buy', type: 'bool', internalType: 'bool' },
          {
            name: 'leverage',
            type: 'uint256',
            internalType: 'uint256',
          },
          { name: 'tp', type: 'uint256', internalType: 'uint256' },
          { name: 'sl', type: 'uint256', internalType: 'uint256' },
          {
            name: 'timestamp',
            type: 'uint256',
            internalType: 'uint256',
          },
        ],
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'usdOI',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'usdc',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IERC20' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'vaultManager',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract IVaultManager',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'walletOI',
    inputs: [{ name: '_trader', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'withinExposureLimits',
    inputs: [
      { name: '_trader', type: 'address', internalType: 'address' },
      { name: '_pairIndex', type: 'uint256', internalType: 'uint256' },
      {
        name: '_leveragedPos',
        type: 'uint256',
        internalType: 'uint256',
      },
      { name: '_buy', type: 'bool', internalType: 'bool' },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'AddressUpdated',
    inputs: [
      {
        name: 'name',
        type: 'string',
        indexed: false,
        internalType: 'string',
      },
      {
        name: 'a',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'FeesCharged',
    inputs: [
      {
        name: '_trader',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: '_pairIndex',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: '_buy',
        type: 'bool',
        indexed: false,
        internalType: 'bool',
      },
      {
        name: 'fee',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'FeesClaimed',
    inputs: [
      {
        name: 'govTreasury',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'govFees',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'devTreasury',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'devFees',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Initialized',
    inputs: [
      {
        name: 'version',
        type: 'uint8',
        indexed: false,
        internalType: 'uint8',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'MarketOpenCanceled',
    inputs: [
      {
        name: 'orderId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'trader',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'pairIndex',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'NumberUpdated',
    inputs: [
      {
        name: 'name',
        type: 'string',
        indexed: false,
        internalType: 'string',
      },
      {
        name: 'value',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'NumberUpdatedPair',
    inputs: [
      {
        name: 'name',
        type: 'string',
        indexed: false,
        internalType: 'string',
      },
      {
        name: 'pairIndex',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'value',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OIUpdated',
    inputs: [
      {
        name: '_open',
        type: 'bool',
        indexed: false,
        internalType: 'bool',
      },
      {
        name: '_long',
        type: 'bool',
        indexed: false,
        internalType: 'bool',
      },
      {
        name: '_pairIndex',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: '_leveragedPos',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: '_price',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RebateClaimed',
    inputs: [
      {
        name: 'referrer',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'amount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SupportedTokenAdded',
    inputs: [
      {
        name: 'a',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'TradeReferred',
    inputs: [
      {
        name: '_trader',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: '_referrer',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: '_leveragedPosition',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: '_traderFeePostDiscount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: '_startingFees',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: '_referrerRebate',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: '_pairIndex',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'TradingContractAdded',
    inputs: [
      {
        name: 'a',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'TradingContractRemoved',
    inputs: [
      {
        name: 'a',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
] as const;
