import { Address } from "viem";

export type DecreasePosition = {
  account: Address;
  market: Address;
  collateralToken: Address;
  sizeInUsd: string;
  sizeInTokens: string;
  collateralAmount: string;
  borrowingFactor: string;
  fundingFeeAmountPerSize: string;
  longTokenClaimableFundingAmountPerSize: string;
  shortTokenClaimableFundingAmountPerSize: string;
  executionPrice: string;
  "indexTokenPrice.max": string;
  "indexTokenPrice.min": string;
  "collateralTokenPrice.max": string;
  "collateralTokenPrice.min": string;
  sizeDeltaUsd: string;
  sizeDeltaInTokens: string;
  collateralDeltaAmount: string;
  "values.priceImpactDiffUsd": string;
  orderType: string;
  decreasedAtTime: string;
  priceImpactUsd: string;
  basePnlUsd: string;
  uncappedBasePnlUsd: string;
  isLong: boolean;
  orderKey: string;
  positionKey: string;
};

export type IncreasePosition = {
  account: Address;
  market: Address;
  collateralToken: Address;
  sizeInUsd: string;
  sizeInTokens: string;
  collateralAmount: string;
  borrowingFactor: string;
  fundingFeeAmountPerSize: string;
  longTokenClaimableFundingAmountPerSize: string;
  shortTokenClaimableFundingAmountPerSize: string;
  executionPrice: string;
  "indexTokenPrice.max": string;
  "indexTokenPrice.min": string;
  "collateralTokenPrice.max": string;
  "collateralTokenPrice.min": string;
  sizeDeltaUsd: string;
  sizeDeltaInTokens: string;
  orderType: string;
  increasedAtTime: string;
  collateralDeltaAmount: string;
  priceImpactUsd: string;
  priceImpactAmount: string;
  isLong: boolean;
  orderKey: string;
  positionKey: string;
};
